/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicFeaturesRouteImport } from './routes/api/public/features'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicTestimonialsRouteImport } from './routes/api/public/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeaturesRoute = ApiPublicFeaturesRouteImport.update({
  id: '/api/public/features',
  path: '/api/public/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestimonialsRoute = ApiPublicTestimonialsRouteImport.update({
  id: '/api/public/testimonials',
  path: '/api/public/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/features'
    | '/api/public/leads'
    | '/api/public/stats'
    | '/api/public/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/features'
    | '/api/public/leads'
    | '/api/public/stats'
    | '/api/public/testimonials'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/features'
    | '/api/public/leads'
    | '/api/public/stats'
    | '/api/public/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicFeaturesRoute: typeof ApiPublicFeaturesRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiPublicTestimonialsRoute: typeof ApiPublicTestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/features': {
      id: '/api/public/features'
      path: '/api/public/features'
      fullPath: '/api/public/features'
      preLoaderRoute: typeof ApiPublicFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/testimonials': {
      id: '/api/public/testimonials'
      path: '/api/public/testimonials'
      fullPath: '/api/public/testimonials'
      preLoaderRoute: typeof ApiPublicTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicFeaturesRoute: ApiPublicFeaturesRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiPublicTestimonialsRoute: ApiPublicTestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
